---
- name:           Install local repos
  copy:           src=./nginx.repo
                  dest=/etc/yum.repos.d/nginx.repo
                  backup=yes

- name:           Opruimen oude backup bestanden
  shell:          find /etc/yum.repos.d/ -maxdepth 1 -iname "nginx.repo.*@*~" -type f | sort | head -n-2 | xargs rm -f
  changed_when:   false

- name:           Install nginx
  yum:            name=nginx
                  state=present
  notify:         restart nginx

- name:           Automatisch starten nginx
  service:        name=nginx enabled=yes

- name:           Installeren default nginx config
  copy:           src=./default.conf
                  dest=/etc/nginx/conf.d/default.conf
  notify:         restart nginx
  when:           nginx_default == true

- name:           Default nginx config verwijderen
  file:           path=/etc/nginx/conf.d/default.conf
                  state=absent
  when:           nginx_default == false

- name:           Zorgen dat de nginx log's worden opgeruimd
  copy:           src=./logrotate.conf
                  dest=/etc/logrotate.d/nginx-custom
